# Generated by Django 4.1.7 on 2023-04-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32, verbose_name='Имя')),
                ('Surname', models.CharField(max_length=32, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('Tag', models.CharField(max_length=16, verbose_name='Метка')),
                ('Content', models.TextField(verbose_name='Содержимое')),
                ('Published', models.TimeField(verbose_name='Дата Публикации')),
                ('Views', models.IntegerField(verbose_name='Количество Просмотров')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SABAH.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
