# Generated by Django 4.1.7 on 2023-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SABAH', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['Name', 'Surname'], name='SABAH_autho_Name_c47434_idx'),
        ),
    ]
