# Generated by Django 4.1.7 on 2023-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SABAH', '0002_author_sabah_autho_name_c47434_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='SABAH_autho_Name_c47434_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='Published',
            field=models.DateTimeField(verbose_name='Дата Публикации'),
        ),
    ]
