# Generated by Django 4.1.7 on 2023-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SABAH', '0003_remove_author_sabah_autho_name_c47434_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Views',
            field=models.IntegerField(default=0, verbose_name='Количество Просмотров'),
        ),
    ]
